### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by daniarjona4** [blacktop/malice#22]
I have a doubt, inside malice is there any antivirus/antimalware that works on acces(can scan all the traffic)? or all only can scan files or directories?

thanks!

**Comment by blacktop** [comment]
Malice's journey continues here - https://github.com/maliceio/malice

You can watch a folder with the `malice watch` command and I am going to add integration with BroIDS so you can attach to a tap and stream files from the network into malice, in the mean time you could have bro or suricata or ICAP put files into the watch folder from the stream.
